// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzKmvMzZ9oD_qCLYG818Sr43iLMNvVmac',
    appId: '1:741805447766:web:86177b9a7fc453fd5479f7',
    messagingSenderId: '741805447766',
    projectId: 'fn-solution-org',
    authDomain: 'fn-solution-org.firebaseapp.com',
    storageBucket: 'fn-solution-org.firebasestorage.app',
    measurementId: 'G-YE2RF8V0XG',
    databaseURL: 'https://fn-solution-org-default-rtdb.firebaseio.com/'
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDhXFRPtT1XiE6PEAbFsUjKq8su9lDZy0',
    appId: '1:741805447766:android:7c25426ce9acd5a25479f7',
    messagingSenderId: '741805447766',
    projectId: 'fn-solution-org',
    storageBucket: 'fn-solution-org.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaLR2HA-S6Huya7CtCfjIKZR5jICAz8B0',
    appId: '1:741805447766:ios:bdbd34e62ae381935479f7',
    messagingSenderId: '741805447766',
    projectId: 'fn-solution-org',
    storageBucket: 'fn-solution-org.firebasestorage.app',
    iosBundleId: 'com.example.fnsolutions',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBaLR2HA-S6Huya7CtCfjIKZR5jICAz8B0',
    appId: '1:741805447766:ios:bdbd34e62ae381935479f7',
    messagingSenderId: '741805447766',
    projectId: 'fn-solution-org',
    storageBucket: 'fn-solution-org.firebasestorage.app',
    iosBundleId: 'com.example.fnsolutions',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBzKmvMzZ9oD_qCLYG818Sr43iLMNvVmac',
    appId: '1:741805447766:web:e05c53dd626361e85479f7',
    messagingSenderId: '741805447766',
    projectId: 'fn-solution-org',
    authDomain: 'fn-solution-org.firebaseapp.com',
    storageBucket: 'fn-solution-org.firebasestorage.app',
    measurementId: 'G-BP3QDLCHN6',
  );
}
